make it possible tu use :GpWhisper <LANGUAGE>
Robitx/gp.nvim pull request #125
Opened 2024-04-02 13:50 UTC by teto

so this can be changed on the fly.

Ideally I would like to be able to pass it an existing file too but I wanted to do a minimum first contribution. Also I develop on top of https://github.com/Robitx/gp.nvim/pull/93 which doesn't help

2024-07-16 13:18 UTC, teto commented
@Robitx you mentioned pending comments but I dont see any ? could you precise please

2024-07-16 13:21 UTC, Robitx requested changes

2024-07-16 13:23 UTC, Robitx commented
@teto sorry, I've forgot the review in the pending state :man_facepalming:

2024-07-16 15:32 UTC, teto commented
ha yeah the log commands interrupt the user, quite bad ^^'''
I wish we could have logging to a file though, it's just too helpful to diagnose issues.
What do you think of vendoring https://github.com/nvim-neorocks/rocks.nvim/blob/master/lua/rocks/log.lua (or something else but there doesn't seem to be a clear winner among logging library yet, plenary.nvim''s is bad) ? could be for another PR or this one.

2024-07-17 09:51 UTC, teto commented on lua/gp/init.lua
> +	M.info("Whisper language set to "..language)
removed

2024-07-17 09:51 UTC, teto commented on lua/gp/init.lua
> +	M.info("spawning command: "..cmd)
removed

2024-07-17 09:51 UTC, teto commented on lua/gp/init.lua
> +			M.Whisper("en", function(text)
yes ! done

2024-07-17 09:52 UTC, teto commented
rebased, addressed comments and updated the doc. Tested locally with French and English. Worked nicely.

> For logging I wouldn't drag another dependency just for this

I was not proposing to add a dependency (yet :) ) but just to copy/paste that file into our codebase.

2024-07-17 09:58 UTC, Robitx commented
@teto btw. the `doc/gp.nvim.txt` is made automatically by a CI function, README is the source of truth from which it's made.

2024-07-17 10:07 UTC, Robitx approved these changes

2024-07-17 10:29 UTC, merged